# Generated by Django 4.2.5 on 2023-09-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_photo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='doc_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.doctor'),
        ),
    ]
