# Generated by Django 4.2.5 on 2023-09-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_doctor_doc_photo_alter_booking_doc_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
