# Generated by Django 4.2.5 on 2023-09-30 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.doctor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doc_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
