# Generated by Django 4.2.5 on 2023-09-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_booking_name_alter_booking_doc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
