# Generated by Django 4.2.5 on 2023-09-30 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.doctor'),
        ),
    ]
